apiVersion: v1
kind: ConfigMap
metadata:
  name: dpmui-configmap
  namespace: dpmservice
data:
  nginx.conf: |
    worker_processes 1;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;
    events {
      worker_connections 1024;
    }
    http {
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
      server {
        listen 80;
        server_name dpmservice.pgcloud.com;
        return 301 https://$host$request_uri;
      }
      server {
        listen 443 ssl;
        server_name dpmservice.pgcloud.com;
        ssl_certificate /etc/nginx/tls/tls.crt;
        ssl_certificate_key /etc/nginx/tls/tls.key;
        ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers    HIGH:!aNULL:!MD5;
        access_log /var/log/nginx/access.log main;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }
